import corpus from "../../../Fixtures/Transport/web-geometry-revisions.json";
import { BrowserWASIBridge, WebSocketSceneBridge } from "../dist/index.js";
import { CanvasSurfacePainter } from "../src/CanvasSurfacePainter.ts";
import { DomSurfacePainter } from "../src/DomSurfacePainter.ts";
import { HostGeometrySession } from "../src/HostGeometrySession.ts";
import { SurfacePaintScheduler } from "../src/SurfacePaintScheduler.ts";
import { normalizeWebHostTerminalStyle } from "../src/WebHostTerminalStyle.ts";

// Wire bytes are generated by Swift, not recreated in JavaScript. The socket
// delivers them through the production receive queue and decoder.
class CorpusSocket extends EventTarget {
  binaryType: BinaryType = "arraybuffer";
  readyState = 1;
  send() {}
  close() {
    this.readyState = 3;
  }
  deliver(record: string) {
    this.dispatchEvent(
      new MessageEvent("message", { data: new Blob([record]) }),
    );
  }
  override addEventListener(type: string, listener: (event: any) => void) {
    super.addEventListener(type, listener);
  }
  override removeEventListener(type: string, listener: (event: any) => void) {
    super.removeEventListener(type, listener);
  }
}

window.runGeometryCorpus = async (transport, renderer) => {
  const socket = new CorpusSocket();
  const bridge =
    transport === "wasi"
      ? new BrowserWASIBridge({ sceneId: "corpus", columns: 4, rows: 2 })
      : new WebSocketSceneBridge({
          sceneId: "corpus",
          token: "fixture",
          baseURL: location.href,
          webSocketFactory: () => socket,
        });
  const surface = document.createElement(renderer === "dom" ? "div" : "canvas");
  surface.style.cssText = "position:relative;width:40px;height:48px";
  document.body.append(surface);
  const painter =
    renderer === "dom" ? new DomSurfacePainter() : new CanvasSurfacePainter();
  if (painter instanceof DomSurfacePainter) painter.attach(surface);
  else painter.attach(surface as HTMLCanvasElement, () => {});
  const session = new HostGeometrySession();
  const painted: number[] = [];
  const decoded: number[] = [];
  const announcements: string[] = [];
  const scheduler = new SurfacePaintScheduler(
    undefined,
    (request) => {
      session.didPresent(request.frame);
      painted.push(request.frame!.geometryRevision!);
      announcements.push(
        ...request.accessibilityAnnouncements.map((item) => item.message),
      );
      painter.paint(
        {
          columns: 4,
          rows: 2,
          cellWidth: 10,
          cellHeight: 24,
          style: normalizeWebHostTerminalStyle({ fontSize: 16 }),
        },
        request.frame,
        request.damage,
        request.recoveredImagePayloadIds,
      );
    },
    (frame) => session.canPresent(frame),
  );
  bridge.bindOutput({
    presentSurface(frame, recovered) {
      decoded.push(frame.geometryRevision!);
      session.observe(frame);
      scheduler.present(frame, recovered);
    },
  });
  for (const entry of corpus.cases) {
    if (entry.name === "new-session-acknowledgement") {
      session.resetConnection();
      scheduler.resetSession();
    }
    // The late response must update the decoder baseline without replacing
    // the newer layout already displayed.
    if (entry.geometryRevision > 0 && entry.name !== "late-old-layout") {
      session.request({
        revision: entry.geometryRevision,
        columns: 4,
        rows: 2,
        cellWidth: 10,
        cellHeight: 24,
      });
    }
    const expectedDecoded =
      decoded.length + (entry.expected === "surface" ? 1 : 0);
    if (bridge instanceof BrowserWASIBridge) bridge.stdout.write(entry.record);
    else socket.deliver(entry.record);
    const deadline = performance.now() + 1000;
    do {
      await new Promise((resolve) => setTimeout(resolve, 0));
    } while (decoded.length < expectedDecoded && performance.now() < deadline);
    if (decoded.length !== expectedDecoded)
      throw new Error(`Corpus delivery did not settle: ${entry.name}`);
  }
  const result = {
    decoded,
    painted,
    announcements,
    text: renderer === "dom" ? surface.textContent : undefined,
    children: surface.childElementCount,
  };
  scheduler.dispose();
  painter.dispose?.();
  bridge.dispose();
  surface.remove();
  return result;
};

declare global {
  interface Window {
    runGeometryCorpus(
      transport: "wasi" | "websocket",
      renderer: "dom" | "canvas",
    ): Promise<{
      decoded: number[];
      painted: number[];
      announcements: string[];
      text: string | null | undefined;
      children: number;
    }>;
  }
}
