import { canRenderBoxDrawing } from "./BoxDrawingRenderer.ts";
import { DomGlyphBackground } from "./DomGlyphBackground.ts";
import { admitsImagePayload } from "./ImageAllocationBudget.ts";
import {
  isSupportedImageFormat,
  normalizeScalingMode,
} from "./normalizeWireTokens.ts";
import { registerDomSurfacePainterConformanceControl } from "./SurfacePainterConformanceControl.ts";
import {
  resolvedSurfaceBackground,
  resolvedSurfaceForeground,
  type SurfaceMetrics,
  type WebHostSurfacePainter,
} from "./SurfaceRenderer.ts";
import { fontForStyle } from "./SurfaceTypography.ts";
import {
  isWebHostImageRecoveryId,
  type WebHostImagePayloadRequestHandler,
  type WebHostSurfaceDamage,
  type WebHostSurfaceFrame,
  type WebHostSurfaceImage,
  type WebHostSurfaceLineStyle,
  type WebHostSurfaceStyle,
} from "./WebHostSurfaceTransport.ts";
import { webTUITerminalBackgroundColor } from "./WebHostTerminalStyle.ts";

interface RenderedImage {
  container: HTMLElement;
  image: HTMLElement;
  source: string;
}

export interface DomSurfacePainterOptions {
  /** Overrides anchor activation, including app-specific URL schemes. */
  onOpenHyperlink?: (url: string) => void;
  /**
   * Reports supported, positive-area image IDs absent from the retained DOM
   * cache. Returning the admitted subset lets bounded transports keep overflow
   * IDs eligible on the next presentation frame; `void` preserves legacy
   * all-accepted behavior for custom hosts.
   */
  onImagePayloadMiss?: WebHostImagePayloadRequestHandler;
}

/**
 * Draws SwiftTUI surface frames as a DOM element tree instead of canvas
 * pixels: one absolutely positioned row container per grid row, one `<span>`
 * per wire lead cell, and `<img>` elements for surface images.
 *
 * Rendering cells as real text buys what canvas cannot offer — the browser's
 * own font shaping and fallback (emoji, CJK), crisp text at any page zoom, an
 * inspectable tree, and native text selection. Geometric box/block/Braille
 * glyphs use SVG backgrounds generated by the Canvas painter's drawing rules.
 *
 * Damage handling mirrors the canvas painter at row granularity: a frame
 * carrying scoped damage patches only the touched rows; geometry or style
 * changes restyle all rows while retaining unchanged text nodes. Each lead cell
 * keeps its supplied Unicode text and span, without advance correction. Resolved styles
 * and geometric backgrounds each have a 512-entry, per-painter cache.
 */
export class DomSurfacePainter implements WebHostSurfacePainter {
  private readonly onImagePayloadMiss: WebHostImagePayloadRequestHandler;
  private root?: HTMLElement;
  private rowsLayer?: HTMLElement;
  private imagesLayer?: HTMLElement;
  private rowElements: HTMLElement[] = [];
  private cells: Map<number, HTMLElement>[] = [];
  private renderedImages = new Map<string, RenderedImage>();
  private appliedMetricsKey?: string;
  private renderedGridKey?: string;
  private renderedLinksKey?: string;
  private readonly linkCells = new Map<number, string>();
  private hasRenderedFrame = false;
  private reportedMissingImageIds = new Set<string>();
  private lastImageRecoveryFrame?: WebHostSurfaceFrame;
  private lastEpoch?: number;
  private readonly glyphs = new DomGlyphBackground();
  private readonly styleCache = new Map<string, Partial<CSSStyleDeclaration>>();
  private appliedCellStyles = new WeakMap<HTMLElement, string>();
  private readonly onOpenHyperlink?: (url: string) => void;

  constructor(options: DomSurfacePainterOptions = {}) {
    this.onOpenHyperlink = options.onOpenHyperlink;
    this.onImagePayloadMiss = options.onImagePayloadMiss ?? (() => {});
    registerDomSurfacePainterConformanceControl(this, {
      evictImages: (ids) => {
        for (const id of ids) {
          this.renderedImages.get(id)?.container.remove();
          this.renderedImages.delete(id);
          this.reportedMissingImageIds.delete(id);
        }
      },
      visibleImageIDs: () => [...this.renderedImages.keys()].sort(),
    });
  }

  /**
   * Binds the container the painter renders into. The runtime owns the
   * container's size; the painter owns everything inside it.
   */
  attach(root: HTMLElement): void {
    this.root = root;

    const rowsLayer = createElement("div");
    rowsLayer.className = "webhost-scene__surface-rows";
    fillContainer(rowsLayer.style);

    const imagesLayer = createElement("div");
    imagesLayer.className = "webhost-scene__surface-images";
    fillContainer(imagesLayer.style);
    imagesLayer.style.pointerEvents = "none";

    this.rowsLayer = rowsLayer;
    this.imagesLayer = imagesLayer;
    root.replaceChildren(rowsLayer, imagesLayer);
    this.rowElements = [];
    this.cells = [];
    this.renderedImages = new Map();
    this.appliedMetricsKey = undefined;
    this.renderedGridKey = undefined;
    this.renderedLinksKey = undefined;
    this.hasRenderedFrame = false;
    this.reportedMissingImageIds.clear();
    this.lastImageRecoveryFrame = undefined;
    this.lastEpoch = undefined;
  }

  paint(
    metrics: SurfaceMetrics,
    frame: WebHostSurfaceFrame | undefined,
    damage?: WebHostSurfaceDamage,
    _recoveredImagePayloadIds?: readonly string[],
  ): void {
    const root = this.root;
    const rowsLayer = this.rowsLayer;
    if (!root || !rowsLayer) {
      return;
    }
    // Selection queries can synchronize layout. Read once before mutations,
    // then use DOM Range intersection (no geometry reads) during the patch.
    const clearSelection = selectionInvalidator();

    if (frame?.epoch !== undefined && frame.epoch !== this.lastEpoch) {
      this.lastEpoch = frame.epoch;
      this.reportedMissingImageIds.clear();
    }

    const metricsKey = metricsKeyFor(metrics);
    const metricsChanged = metricsKey !== this.appliedMetricsKey;
    if (metricsChanged) {
      this.styleCache.clear();
      this.appliedCellStyles = new WeakMap();
      this.glyphs.clear();
      this.applyRootStyle(root, metrics);
      this.appliedMetricsKey = metricsKey;
    }

    if (!frame) {
      clearSelection(rowsLayer);
      this.rowElements = [];
      this.cells = [];
      this.linkCells.clear();
      rowsLayer.replaceChildren();
      this.lastImageRecoveryFrame = undefined;
      this.reconcileImages([], metrics, false);
      this.renderedGridKey = undefined;
      this.renderedLinksKey = undefined;
      this.hasRenderedFrame = false;
      return;
    }

    const gridKey = `${frame.width}x${frame.height}x${frame.rows.length}`;
    const linksKey = JSON.stringify([
      frame.width,
      frame.links,
      frame.linkTargets,
    ]);
    const linksChanged = linksKey !== this.renderedLinksKey;
    this.renderedLinksKey = linksKey;
    if (linksChanged) {
      this.linkCells.clear();
      for (const [y, runs] of frame.links ?? []) {
        for (const [x, span, targetIndex] of runs) {
          const target = frame.linkTargets?.[targetIndex];
          if (target === undefined) continue;
          for (
            let column = Math.max(0, x);
            column < Math.min(frame.width, x + span);
            column += 1
          ) {
            const key = y * frame.width + column;
            if (!this.linkCells.has(key)) this.linkCells.set(key, target);
          }
        }
      }
    }
    const fullRepaint =
      linksChanged ||
      metricsChanged ||
      !this.hasRenderedFrame ||
      gridKey !== this.renderedGridKey ||
      !damage ||
      damage.requiresFullTextRepaint ||
      damage.requiresFullGraphicsReplay;
    this.renderedGridKey = gridKey;

    if (fullRepaint) {
      for (let y = this.rowElements.length; y > frame.rows.length; y -= 1) {
        const row = this.rowElements[y - 1];
        if (row) clearSelection(row);
        row?.remove();
        this.cells.pop();
      }
      this.rowElements.length = Math.min(
        this.rowElements.length,
        frame.rows.length,
      );
      for (let y = 0; y < frame.rows.length; y += 1) {
        this.rebuildRow(y, frame, metrics, clearSelection);
      }
    } else {
      for (const [row] of damage.textRows) {
        if (row < 0 || row >= frame.rows.length) {
          continue;
        }
        this.rebuildRow(row, frame, metrics, clearSelection);
      }
    }

    const allowRecoveryRequests = frame !== this.lastImageRecoveryFrame;
    this.lastImageRecoveryFrame = frame;
    this.reconcileImages(frame.images ?? [], metrics, allowRecoveryRequests);
    this.hasRenderedFrame = true;
  }

  invalidateFontMetrics(): void {
    this.appliedMetricsKey = undefined;
  }

  dispose(): void {
    this.styleCache.clear();
    this.appliedCellStyles = new WeakMap();
    this.glyphs.clear();
    this.linkCells.clear();
    this.root?.replaceChildren();
    this.root = undefined;
    this.rowsLayer = undefined;
    this.imagesLayer = undefined;
    this.rowElements = [];
    this.cells = [];
    this.renderedImages.clear();
    this.reportedMissingImageIds.clear();
    this.lastImageRecoveryFrame = undefined;
  }

  private rebuildRow(
    y: number,
    frame: WebHostSurfaceFrame,
    metrics: SurfaceMetrics,
    clearSelection: (element: HTMLElement) => void,
  ): void {
    const rowElement = this.ensureRowElement(y, metrics);
    const previous = this.cells[y] ?? new Map<number, HTMLElement>();
    const next = new Map<number, HTMLElement>();
    const retainedColumns = new Set(
      (frame.rows[y] ?? []).map((cell) => cell[0]),
    );
    // Remove absent predecessors before reconciling positions. Moving a
    // retained selected node to fill their old slot would collapse its Range.
    for (const [x, element] of previous) {
      if (!retainedColumns.has(x)) {
        clearSelection(element);
        element.remove();
      }
    }
    let position = 0;
    for (const [x, text, span, styleIndex] of frame.rows[y] ?? []) {
      const cellStyle = frame.styles[styleIndex] ?? undefined;
      const target = this.linkCells.get(y * frame.width + x);
      const isLink =
        target !== undefined &&
        (/^https?:/i.test(target) || !!this.onOpenHyperlink);
      const tag = isLink ? "A" : "SPAN";
      let element = previous.get(x);
      if (element && element.tagName !== tag) {
        clearSelection(element);
        element.remove();
        element = undefined;
      }
      if (!element) element = createElement(tag.toLowerCase());
      if (element.textContent !== text) {
        clearSelection(element);
        element.textContent = text;
      }
      const key = JSON.stringify(cellStyle ?? null);
      let resolved = this.styleCache.get(key);
      if (!resolved) {
        resolved = resolveCellStyle(cellStyle, metrics);
        if (this.styleCache.size >= 512)
          this.styleCache.delete(this.styleCache.keys().next().value as string);
        this.styleCache.set(key, resolved);
      }
      const geometricText = canRenderBoxDrawing(text) ? text : "";
      const presentationKey = JSON.stringify([key, x, span, geometricText]);
      if (this.appliedCellStyles.get(element) !== presentationKey) {
        Object.assign(element.style, resolved, {
          left: `${x * metrics.cellWidth}px`,
          width: `${Math.max(1, span) * metrics.cellWidth}px`,
        });
        const glyph = this.glyphs.image(
          geometricText,
          resolved.color ?? "",
          Math.max(1, span) * metrics.cellWidth,
          metrics.cellHeight,
        );
        element.style.backgroundImage = glyph ?? "none";
        element.style.backgroundSize = "100% 100%";
        element.style.backgroundRepeat = "no-repeat";
        // Keep exactly one real text node for native selection/copy/find.
        element.style.color = glyph ? "transparent" : (resolved.color ?? "");
        this.appliedCellStyles.set(element, presentationKey);
      }
      if (isLink && target !== undefined) {
        element.setAttribute("data-surface-link", target);
        element.setAttribute("tabindex", "-1"); // ARIA sidecar owns keyboard accessibility.
        element.setAttribute("rel", "noopener noreferrer");
        element.setAttribute("target", "_blank");
        // Custom schemes only reach the hook, never browser navigation.
        element.setAttribute("href", /^https?:/i.test(target) ? target : "#");
        const activate = (event: MouseEvent) => {
          if (event.altKey || document.getSelection()?.isCollapsed === false) {
            event.preventDefault();
          } else if (this.onOpenHyperlink) {
            event.preventDefault();
            this.onOpenHyperlink(target);
          } else if (!/^https?:/i.test(target)) {
            event.preventDefault();
          }
        };
        element.onclick = activate;
        element.onauxclick = activate;
      }
      next.set(x, element);
      if (rowElement.children[position] !== element) {
        rowElement.insertBefore(element, rowElement.children[position] ?? null);
      }
      position += 1;
    }
    this.cells[y] = next;
  }

  private ensureRowElement(y: number, metrics: SurfaceMetrics): HTMLElement {
    let rowElement = this.rowElements[y];
    if (!rowElement) {
      rowElement = createElement("div");
      rowElement.className = "webhost-scene__surface-row";
      Object.assign(rowElement.style, scopedBoxStyle, {
        font: "inherit",
        lineHeight: "inherit",
        letterSpacing: "0px",
        wordSpacing: "0px",
      });
      rowElement.style.position = "absolute";
      rowElement.style.left = "0";
      this.rowElements[y] = rowElement;
      this.rowsLayer?.appendChild(rowElement);
    }
    rowElement.style.top = `${y * metrics.cellHeight}px`;
    rowElement.style.height = `${metrics.cellHeight}px`;
    rowElement.style.width = `${metrics.columns * metrics.cellWidth}px`;
    return rowElement;
  }

  private applyRootStyle(root: HTMLElement, metrics: SurfaceMetrics): void {
    const style = root.style;
    Object.assign(style, scopedBoxStyle);
    style.position = "relative";
    style.overflow = "hidden";
    style.background = webTUITerminalBackgroundColor(metrics.style);
    style.font = fontForStyle(metrics.style);
    // Set after `font`: the shorthand resets line-height, and the grid needs
    // every row to be exactly one cell tall.
    style.lineHeight = `${metrics.cellHeight}px`;
    style.letterSpacing = "0px";
    style.wordSpacing = "0px";
    style.fontKerning = "none";
    style.fontSynthesis = "none";
    style.direction = "ltr";
    style.unicodeBidi = "isolate";
    // Ligature-capable monospace fonts would merge runs like "->" into one
    // glyph and break the column grid.
    style.fontVariantLigatures = "none";
    style.userSelect = "text";
  }

  private reconcileImages(
    images: WebHostSurfaceImage[],
    metrics: SurfaceMetrics,
    allowRecoveryRequests: boolean,
  ): void {
    const layer = this.imagesLayer;
    if (!layer) {
      return;
    }

    const next = new Map<string, RenderedImage>();
    const currentMissingImageIds = new Set<string>();
    const newlyMissingImageIds = new Set<string>();
    for (const rawImage of images) {
      if (!isSupportedImageFormat(rawImage.format)) {
        continue;
      }
      const image = {
        ...rawImage,
        scalingMode: normalizeScalingMode(rawImage.scalingMode),
      };
      const [boundsX, boundsY, boundsWidth, boundsHeight] = image.bounds;
      const [clipX, clipY, clipWidth, clipHeight] = image.visibleBounds;
      const existing = this.renderedImages.get(image.id);
      if (
        image.dataBase64 !== undefined &&
        !admitsImagePayload(image.dataBase64)
      )
        continue;
      if (
        boundsWidth <= 0 ||
        boundsHeight <= 0 ||
        clipWidth <= 0 ||
        clipHeight <= 0
      ) {
        continue;
      }
      if (!existing && image.dataBase64 === undefined) {
        if (!isWebHostImageRecoveryId(image.id)) {
          continue;
        }
        currentMissingImageIds.add(image.id);
        if (!this.reportedMissingImageIds.has(image.id)) {
          newlyMissingImageIds.add(image.id);
        }
        continue;
      }

      const entry = existing ?? makeImageEntry();
      entry.container.style.left = `${clipX * metrics.cellWidth}px`;
      entry.container.style.top = `${clipY * metrics.cellHeight}px`;
      entry.container.style.width = `${clipWidth * metrics.cellWidth}px`;
      entry.container.style.height = `${clipHeight * metrics.cellHeight}px`;
      entry.image.style.left = `${(boundsX - clipX) * metrics.cellWidth}px`;
      entry.image.style.top = `${(boundsY - clipY) * metrics.cellHeight}px`;
      entry.image.style.width = `${boundsWidth * metrics.cellWidth}px`;
      entry.image.style.height = `${boundsHeight * metrics.cellHeight}px`;
      entry.image.style.opacity = String(normalizedImageOpacity(image.opacity));

      if (image.dataBase64) {
        const source = `data:image/${image.format};base64,${image.dataBase64}`;
        if (entry.source !== source) {
          entry.image.setAttribute("src", source);
          entry.source = source;
        }
      }
      if (!existing) {
        layer.appendChild(entry.container);
      }
      next.set(image.id, entry);
    }

    for (const [id, entry] of this.renderedImages) {
      if (!next.has(id)) {
        entry.container.remove();
      }
    }
    this.renderedImages = next;
    for (const id of this.reportedMissingImageIds) {
      if (!currentMissingImageIds.has(id)) {
        this.reportedMissingImageIds.delete(id);
      }
    }
    if (allowRecoveryRequests && newlyMissingImageIds.size > 0) {
      const candidateIds = [...newlyMissingImageIds].sort();
      const admittedIds = this.onImagePayloadMiss(candidateIds);
      const acceptedIds = Array.isArray(admittedIds)
        ? admittedIds
        : candidateIds;
      const candidates = new Set(candidateIds);
      for (const id of acceptedIds) {
        if (candidates.has(id)) {
          this.reportedMissingImageIds.add(id);
        }
      }
    }
  }
}

function normalizedImageOpacity(opacity: number | undefined): number {
  if (opacity === undefined || !Number.isFinite(opacity)) {
    return 1;
  }
  return Math.max(0, Math.min(1, opacity));
}

/**
 * A change key over everything the rendered tree bakes into element styles —
 * grid geometry, font, and theme colors. A key change invalidates every
 * rendered row, so the next paint restyles the root and rebuilds in full.
 */
function metricsKeyFor(metrics: SurfaceMetrics): string {
  return [
    metrics.columns,
    metrics.rows,
    metrics.cellWidth,
    metrics.cellHeight,
    fontForStyle(metrics.style),
    metrics.style.theme.foreground,
    metrics.style.theme.background,
    metrics.style.theme.windowBackground,
    metrics.style.backgroundOpacity,
  ].join("|");
}

function resolveCellStyle(
  style: WebHostSurfaceStyle | undefined,
  metrics: SurfaceMetrics,
): Partial<CSSStyleDeclaration> {
  const elementStyle = {
    position: "absolute",
    display: "block",
    boxSizing: "border-box",
    padding: "0",
    margin: "0",
    border: "0",
    textIndent: "0",
    textTransform: "none",
    fontFamily: "inherit",
    fontSize: "inherit",
    lineHeight: "inherit",
    letterSpacing: "0px",
    wordSpacing: "0px",
    fontKerning: "none",
    fontSynthesis: "none",
    fontVariantLigatures: "none",
    top: "0",
    height: "100%",
    whiteSpace: "pre",
    overflow: "hidden",
    direction: "ltr",
    unicodeBidi: "isolate",
    color: resolvedSurfaceForeground(style, metrics.style),
    backgroundColor:
      resolvedSurfaceBackground(style, metrics.style) ?? "transparent",
    fontWeight: (style?.em ?? 0) & 1 ? "700" : "normal",
    fontStyle: (style?.em ?? 0) & 2 ? "italic" : "normal",
    opacity: String(style?.opacity ?? 1),
    textDecorationLine: "none",
    textDecorationStyle: "solid",
    textDecorationColor: resolvedSurfaceForeground(style, metrics.style),
  };
  applyTextDecoration(elementStyle as CSSStyleDeclaration, style);
  return elementStyle;
}

function applyTextDecoration(
  elementStyle: CSSStyleDeclaration,
  style: WebHostSurfaceStyle | undefined,
): void {
  const lines: string[] = [];
  if (style?.underline) {
    lines.push("underline");
  }
  if (style?.strikethrough) {
    lines.push("line-through");
  }
  if (lines.length === 0) {
    return;
  }

  elementStyle.textDecorationLine = lines.join(" ");
  const pattern = style?.underline?.pattern ?? style?.strikethrough?.pattern;
  elementStyle.textDecorationStyle = decorationStyleFor(pattern);
  // CSS shares one decoration color across both lines; the underline's color
  // wins when the app styles them differently.
  const color = style?.underline?.color ?? style?.strikethrough?.color;
  if (color) {
    elementStyle.textDecorationColor = color;
  }
}

function decorationStyleFor(
  pattern: WebHostSurfaceLineStyle["pattern"] | undefined,
): string {
  switch (pattern) {
    case "dot":
      return "dotted";
    case "dash":
    case "dashDot":
    case "dashDotDot":
      return "dashed";
    case "double":
      return "double";
    case "curly":
      return "wavy";
    default:
      return "solid";
  }
}

function fillContainer(style: CSSStyleDeclaration): void {
  Object.assign(style, scopedBoxStyle, {
    font: "inherit",
    lineHeight: "inherit",
  });
  style.position = "absolute";
  style.left = "0";
  style.top = "0";
  style.width = "100%";
  style.height = "100%";
}

function makeImageEntry(): RenderedImage {
  const container = createElement("div");
  container.className = "webhost-scene__surface-image";
  Object.assign(container.style, scopedBoxStyle);
  container.style.position = "absolute";
  container.style.overflow = "hidden";

  const image = createElement("img");
  Object.assign(image.style, scopedBoxStyle);
  image.style.position = "absolute";
  image.setAttribute("alt", "");
  image.setAttribute("draggable", "false");
  container.appendChild(image);
  return { container, image, source: "" };
}

const scopedBoxStyle = {
  boxSizing: "border-box",
  margin: "0",
  padding: "0",
  border: "0",
  textAlign: "left",
  textIndent: "0",
  textTransform: "none",
};

function createElement(tagName: string): HTMLElement {
  if (typeof document === "undefined") {
    throw new Error("document is not available");
  }
  return document.createElement(tagName);
}

/** Only a mutation of selected content cancels a live selection. */
function selectionInvalidator(): (element: HTMLElement) => void {
  let selection = globalThis.document?.getSelection?.();
  if (!selection || selection.isCollapsed) return () => {};
  const ranges = Array.from({ length: selection.rangeCount }, (_, index) =>
    selection!.getRangeAt(index),
  );
  return (element) => {
    if (selection && ranges.some((range) => range.intersectsNode(element))) {
      selection.removeAllRanges();
      selection = null;
    }
  };
}
