import { canRenderBoxDrawing } from "./BoxDrawingRenderer.ts";
import { DomGlyphBackground } from "./DomGlyphBackground.ts";
import { imagePayloadMetrics } from "./ImageAllocationBudget.ts";
import {
  isSupportedImageFormat,
  normalizeScalingMode,
} from "./normalizeWireTokens.ts";
import { staticGifBase64 } from "./StaticGif.ts";
import { registerDomSurfacePainterConformanceControl } from "./SurfacePainterConformanceControl.ts";
import {
  resolvedSurfaceBackground,
  resolvedSurfaceForeground,
  type SurfaceMetrics,
  type WebHostSurfacePainter,
} from "./SurfaceRenderer.ts";
import { fontForStyle } from "./SurfaceTypography.ts";
import {
  isWebHostImageRecoveryId,
  type WebHostImagePayloadRequestHandler,
  type WebHostSurfaceCell,
  type WebHostSurfaceDamage,
  type WebHostSurfaceFrame,
  type WebHostSurfaceImage,
  type WebHostSurfaceStyle,
} from "./WebHostSurfaceTransport.ts";
import { webTUITerminalBackgroundColor } from "./WebHostTerminalStyle.ts";

interface RenderedImage {
  id: string;
  container: HTMLElement;
  image: HTMLElement;
  source: string;
  decodedBytes: number;
  payloadBytes: number;
  generation: number;
  state: "pending" | "ready" | "failed" | "evicted";
}

export const MAX_DOM_IMAGE_ENTRIES = 256;
export const MAX_DOM_IMAGE_BYTES = 64 * 1024 * 1024;

export interface DomSurfaceStatistics {
  rows: number;
  cells: number;
  rowSeparators: number;
  decorationNodes: number;
  imageNodes: number;
  styleCacheEntries: number;
  geometryCacheEntries: number;
  decodedImageBytes: number;
  retainedPayloadBytes: number;
  pendingImages: number;
  failedImages: number;
  rejectedImages: number;
}

export interface DomSurfacePainterOptions {
  onResourceLimit?: (message: string) => void;
  /** Overrides anchor activation, including app-specific URL schemes. */
  onOpenHyperlink?: (url: string) => void;
  /**
   * Reports supported, positive-area image IDs absent from the retained DOM
   * cache. Returning the admitted subset lets bounded transports keep overflow
   * IDs eligible on the next presentation frame; `void` preserves legacy
   * all-accepted behavior for custom hosts.
   */
  onImagePayloadMiss?: WebHostImagePayloadRequestHandler;
}

/**
 * Experimental presenter; see the package README for its support boundary.
 *
 * Draws SwiftTUI surface frames as a DOM element tree instead of canvas
 * pixels: one absolutely positioned row container per grid row, one `<span>`
 * per wire lead cell, explicit sparse-space runs, and `<img>` elements for surface images.
 *
 * Rendering cells as real text buys what canvas cannot offer — the browser's
 * own font shaping and fallback (emoji, CJK), crisp text at any page zoom, an
 * inspectable tree, and native text selection. Geometric box/block/Braille
 * glyphs use SVG backgrounds generated by the Canvas painter's drawing rules.
 *
 * Damage handling mirrors the canvas painter at row granularity: a frame
 * carrying scoped damage patches only the touched rows; geometry or style
 * changes restyle all rows while retaining unchanged text nodes. Each lead cell
 * keeps its supplied Unicode text and span, without advance correction. Resolved styles
 * and geometric backgrounds each have a 512-entry, per-painter cache.
 */
export class DomSurfacePainter implements WebHostSurfacePainter {
  private rejectedImages = 0;
  private forcedColors = false;
  private forcedForeground = "CanvasText";
  private readonly reportedLimits = new Set<string>();
  private readonly onImagePayloadMiss: WebHostImagePayloadRequestHandler;
  private root?: HTMLElement;
  private rowsLayer?: HTMLElement;
  private imagesLayer?: HTMLElement;
  private rowElements: HTMLElement[] = [];
  private cells: Map<number, HTMLElement>[] = [];
  private rowBreaks: Text[] = [];
  private renderedImages = new Map<string, RenderedImage>();
  private appliedMetricsKey?: string;
  private renderedGridKey?: string;
  private renderedLinksKey?: string;
  private readonly linkCells = new Map<number, string>();
  private hasRenderedFrame = false;
  private reportedMissingImageIds = new Set<string>();
  private lastImageRecoveryFrame?: WebHostSurfaceFrame;
  private lastEpoch?: number;
  private readonly glyphs = new DomGlyphBackground();
  private readonly styleCache = new Map<string, Partial<CSSStyleDeclaration>>();
  private appliedCellStyles = new WeakMap<HTMLElement, string>();
  private readonly onOpenHyperlink?: (url: string) => void;
  private readonly copySelection = (event: ClipboardEvent) => {
    const selection = document.getSelection();
    if (
      !this.root ||
      !selection ||
      selection.isCollapsed ||
      !event.clipboardData
    )
      return;
    const ranges = Array.from({ length: selection.rangeCount }, (_, index) =>
      selection.getRangeAt(index),
    );
    if (
      ranges.some(
        (range) => !this.root!.contains(range.commonAncestorContainer),
      )
    )
      return;
    // Every gap and row separator is authored in the visible text tree.
    // Native selection serializers otherwise invent engine-specific block
    // newlines. Preserve precisely the selected text offsets, including spaces.
    event.clipboardData.setData(
      "text/plain",
      ranges.map((range) => range.cloneContents().textContent ?? "").join("\n"),
    );
    event.preventDefault();
  };

  constructor(options: DomSurfacePainterOptions = {}) {
    this.onResourceLimit = options.onResourceLimit ?? (() => {});
    this.onOpenHyperlink = options.onOpenHyperlink;
    this.onImagePayloadMiss = options.onImagePayloadMiss ?? (() => {});
    registerDomSurfacePainterConformanceControl(this, {
      evictImages: (ids) => {
        for (const [key, entry] of this.renderedImages) {
          if (!ids.includes(entry.id)) continue;
          entry.container.remove();
          releaseImageEntry(entry);
          this.renderedImages.delete(key);
          this.reportedMissingImageIds.delete(entry.id);
        }
      },
      visibleImageIDs: () =>
        [
          ...new Set(
            [...this.renderedImages.values()].map((entry) => entry.id),
          ),
        ].sort(),
    });
  }

  private readonly onResourceLimit: (message: string) => void;

  get statistics(): DomSurfaceStatistics {
    const images = [...this.renderedImages.values()];
    return {
      rows: this.rowElements.length,
      cells: this.cells.reduce((sum, cells) => sum + cells.size, 0),
      rowSeparators: this.rowBreaks.length,
      decorationNodes: 0, // Bounded SVG backgrounds, no extra live DOM nodes.
      imageNodes: images.length * 2,
      styleCacheEntries: this.styleCache.size,
      geometryCacheEntries: this.glyphs.size,
      decodedImageBytes: images.reduce(
        (sum, image) => sum + image.decodedBytes,
        0,
      ),
      retainedPayloadBytes: images.reduce(
        (sum, image) => sum + image.payloadBytes,
        0,
      ),
      pendingImages: images.filter((image) => image.state === "pending").length,
      failedImages: images.filter((image) => image.state === "failed").length,
      rejectedImages: this.rejectedImages,
    };
  }

  private rejectImage(reason: string): void {
    this.rejectedImages = Math.min(
      Number.MAX_SAFE_INTEGER,
      this.rejectedImages + 1,
    );
    if (this.reportedLimits.has(reason)) return;
    this.reportedLimits.add(reason);
    this.onResourceLimit(reason);
  }

  /**
   * Binds the container the painter renders into. The runtime owns the
   * container's size; the painter owns everything inside it.
   */
  attach(root: HTMLElement): void {
    this.root = root;
    document.addEventListener?.("copy", this.copySelection);

    const rowsLayer = createElement("div");
    rowsLayer.className = "webhost-scene__surface-rows";
    fillContainer(rowsLayer.style);

    const imagesLayer = createElement("div");
    imagesLayer.className = "webhost-scene__surface-images";
    fillContainer(imagesLayer.style);
    imagesLayer.style.pointerEvents = "none";

    this.rowsLayer = rowsLayer;
    this.imagesLayer = imagesLayer;
    root.replaceChildren(rowsLayer, imagesLayer);
    this.rowElements = [];
    this.cells = [];
    this.rowBreaks = [];
    this.renderedImages = new Map();
    this.appliedMetricsKey = undefined;
    this.renderedGridKey = undefined;
    this.renderedLinksKey = undefined;
    this.hasRenderedFrame = false;
    this.reportedMissingImageIds.clear();
    this.lastImageRecoveryFrame = undefined;
    this.lastEpoch = undefined;
  }

  paint(
    metrics: SurfaceMetrics,
    frame: WebHostSurfaceFrame | undefined,
    damage?: WebHostSurfaceDamage,
    _recoveredImagePayloadIds?: readonly string[],
  ): void {
    const root = this.root;
    const rowsLayer = this.rowsLayer;
    if (!root || !rowsLayer) {
      return;
    }
    // Selection queries can synchronize layout. Read once before mutations,
    // then use DOM Range intersection (no geometry reads) during the patch.
    const clearSelection = selectionInvalidator();

    if (frame?.epoch !== undefined && frame.epoch !== this.lastEpoch) {
      this.lastEpoch = frame.epoch;
      this.reportedMissingImageIds.clear();
    }

    const forcedColors =
      globalThis.matchMedia?.("(forced-colors: active)").matches ?? false;
    const currentForcedForeground =
      forcedColors && this.forcedColors
        ? globalThis.getComputedStyle?.(root).color
        : undefined;
    this.forcedColors = forcedColors;
    const metricsKey = `${metricsKeyFor(metrics)}|${forcedColors}`;
    const metricsChanged =
      metricsKey !== this.appliedMetricsKey ||
      (currentForcedForeground !== undefined &&
        currentForcedForeground !== this.forcedForeground);
    if (metricsChanged) {
      this.styleCache.clear();
      this.appliedCellStyles = new WeakMap();
      this.glyphs.clear();
      this.applyRootStyle(root, metrics);
      if (forcedColors)
        this.forcedForeground =
          globalThis.getComputedStyle?.(root).color ?? "CanvasText";
      this.appliedMetricsKey = metricsKey;
    }

    if (!frame) {
      clearSelection(rowsLayer);
      this.rowElements = [];
      this.cells = [];
      this.rowBreaks = [];
      this.linkCells.clear();
      rowsLayer.replaceChildren();
      this.lastImageRecoveryFrame = undefined;
      this.reconcileImages([], metrics, false);
      this.renderedGridKey = undefined;
      this.renderedLinksKey = undefined;
      this.hasRenderedFrame = false;
      return;
    }

    const gridKey = `${frame.width}x${frame.height}x${frame.rows.length}`;
    const linksKey = JSON.stringify([
      frame.width,
      frame.links,
      frame.linkTargets,
    ]);
    const linksChanged = linksKey !== this.renderedLinksKey;
    this.renderedLinksKey = linksKey;
    if (linksChanged) {
      this.linkCells.clear();
      for (const [y, runs] of frame.links ?? []) {
        for (const [x, span, targetIndex] of runs) {
          const target = frame.linkTargets?.[targetIndex];
          if (target === undefined) continue;
          for (
            let column = Math.max(0, x);
            column < Math.min(frame.width, x + span);
            column += 1
          ) {
            const key = y * frame.width + column;
            if (!this.linkCells.has(key)) this.linkCells.set(key, target);
          }
        }
      }
    }
    const fullRepaint =
      linksChanged ||
      metricsChanged ||
      !this.hasRenderedFrame ||
      gridKey !== this.renderedGridKey ||
      !damage ||
      damage.requiresFullTextRepaint ||
      damage.requiresFullGraphicsReplay;
    this.renderedGridKey = gridKey;

    if (fullRepaint) {
      for (let y = this.rowElements.length; y > frame.rows.length; y -= 1) {
        const row = this.rowElements[y - 1];
        if (row) clearSelection(row);
        row?.remove();
        this.cells.pop();
        this.rowBreaks.pop();
      }
      this.rowElements.length = Math.min(
        this.rowElements.length,
        frame.rows.length,
      );
      for (let y = 0; y < frame.rows.length; y += 1) {
        this.rebuildRow(y, frame, metrics, clearSelection);
      }
    } else {
      for (const [row] of damage.textRows) {
        if (row < 0 || row >= frame.rows.length) {
          continue;
        }
        this.rebuildRow(row, frame, metrics, clearSelection);
      }
    }

    const allowRecoveryRequests = frame !== this.lastImageRecoveryFrame;
    this.lastImageRecoveryFrame = frame;
    this.reconcileImages(frame.images ?? [], metrics, allowRecoveryRequests);
    this.hasRenderedFrame = true;
  }

  invalidateFontMetrics(): void {
    this.appliedMetricsKey = undefined;
  }

  dispose(): void {
    document.removeEventListener?.("copy", this.copySelection);
    this.styleCache.clear();
    this.appliedCellStyles = new WeakMap();
    this.glyphs.clear();
    this.linkCells.clear();
    this.root?.replaceChildren();
    this.root = undefined;
    this.rowsLayer = undefined;
    this.imagesLayer = undefined;
    this.rowElements = [];
    this.cells = [];
    this.rowBreaks = [];
    for (const entry of this.renderedImages.values()) releaseImageEntry(entry);
    this.renderedImages.clear();
    this.reportedMissingImageIds.clear();
    this.lastImageRecoveryFrame = undefined;
  }

  private rebuildRow(
    y: number,
    frame: WebHostSurfaceFrame,
    metrics: SurfaceMetrics,
    clearSelection: (element: HTMLElement) => void,
  ): void {
    const rowElement = this.ensureRowElement(y, metrics);
    const previous = this.cells[y] ?? new Map<number, HTMLElement>();
    const next = new Map<number, HTMLElement>();
    const rowCells = copyableRow(frame.rows[y] ?? [], frame.width);
    const retainedColumns = new Set(rowCells.map((cell) => cell[0]));
    // Remove absent predecessors before reconciling positions. Moving a
    // retained selected node to fill their old slot would collapse its Range.
    for (const [x, element] of previous) {
      if (!retainedColumns.has(x)) {
        clearSelection(element);
        element.remove();
      }
    }
    let position = 0;
    for (const [x, text, span, styleIndex] of rowCells) {
      const cellStyle = frame.styles[styleIndex] ?? undefined;
      const target = this.linkCells.get(y * frame.width + x);
      const isLink =
        target !== undefined &&
        (/^https?:/i.test(target) || !!this.onOpenHyperlink);
      const tag = isLink ? "A" : "SPAN";
      let element = previous.get(x);
      if (element && element.tagName !== tag) {
        clearSelection(element);
        element.remove();
        element = undefined;
      }
      if (!element) element = createElement(tag.toLowerCase());
      if (element.textContent !== text) {
        clearSelection(element);
        // Keep the existing text/layout object when its contents change.
        // textContent's replace-all operation needlessly destroys and rebuilds
        // every text node in a full-frame update.
        const node = element.firstChild;
        if (node?.nodeType === 3) node.nodeValue = text;
        else element.textContent = text;
      }
      const key = JSON.stringify(cellStyle ?? null);
      let resolved = this.styleCache.get(key);
      if (!resolved) {
        resolved = resolveCellStyle(
          cellStyle,
          metrics,
          this.forcedColors ? this.forcedForeground : undefined,
        );
        if (this.styleCache.size >= 512)
          this.styleCache.delete(this.styleCache.keys().next().value as string);
        this.styleCache.set(key, resolved);
      }
      const geometricText = canRenderBoxDrawing(text) ? text : "";
      const presentationKey = JSON.stringify([key, x, span, geometricText]);
      if (this.appliedCellStyles.get(element) !== presentationKey) {
        Object.assign(element.style, resolved, {
          left: `${x * metrics.cellWidth}px`,
          width: `${Math.max(1, span) * metrics.cellWidth}px`,
          // Cancel flow advance so each relative offset starts at the row
          // origin. This prevents WebKit zoom rounding from accumulating,
          // while retaining inline text search in Firefox and WebKit.
          marginRight: `${-Math.max(1, span) * metrics.cellWidth}px`,
        });
        const glyph = this.glyphs.image(
          geometricText,
          resolved.color ?? "",
          Math.max(1, span) * metrics.cellWidth,
          metrics.cellHeight,
          this.forcedColors
            ? {
                ...cellStyle,
                underline: cellStyle?.underline
                  ? { ...cellStyle.underline, color: this.forcedForeground }
                  : undefined,
                strikethrough: cellStyle?.strikethrough
                  ? { ...cellStyle.strikethrough, color: this.forcedForeground }
                  : undefined,
              }
            : cellStyle,
          x * metrics.cellWidth,
        );
        element.style.backgroundImage = glyph ?? "none";
        element.style.backgroundSize = "100% 100%";
        element.style.backgroundRepeat = "no-repeat";
        // Keep exactly one real text node for native selection/copy/find.
        element.style.color = geometricText
          ? "transparent"
          : (resolved.color ?? "");
        this.appliedCellStyles.set(element, presentationKey);
      }
      if (
        isLink &&
        target !== undefined &&
        element.getAttribute("data-surface-link") !== target
      ) {
        element.setAttribute("data-surface-link", target);
        element.setAttribute("tabindex", "-1"); // ARIA sidecar owns keyboard accessibility.
        element.setAttribute("rel", "noopener noreferrer");
        element.setAttribute("target", "_blank");
        // Custom schemes only reach the hook, never browser navigation.
        element.setAttribute("href", /^https?:/i.test(target) ? target : "#");
        const activate = (event: MouseEvent) => {
          if (event.altKey || document.getSelection()?.isCollapsed === false) {
            event.preventDefault();
          } else if (this.onOpenHyperlink) {
            event.preventDefault();
            this.onOpenHyperlink(target);
          } else if (!/^https?:/i.test(target)) {
            event.preventDefault();
          }
        };
        element.onclick = activate;
        element.onauxclick = activate;
      }
      next.set(x, element);
      if (rowElement.children[position] !== element) {
        rowElement.insertBefore(element, rowElement.children[position] ?? null);
      }
      position += 1;
    }
    this.cells[y] = next;
    let rowBreak = this.rowBreaks[y];
    if (y < frame.rows.length - 1) {
      if (!rowBreak) {
        rowBreak = document.createTextNode("\n");
        rowElement.appendChild(rowBreak);
        this.rowBreaks[y] = rowBreak;
      }
    } else if (rowBreak) {
      clearSelection(rowElement);
      rowBreak.remove();
      this.rowBreaks.length = y;
    }
  }

  private ensureRowElement(y: number, metrics: SurfaceMetrics): HTMLElement {
    let rowElement = this.rowElements[y];
    if (!rowElement) {
      rowElement = createElement("div");
      rowElement.className = "webhost-scene__surface-row";
      Object.assign(rowElement.style, scopedBoxStyle, {
        font: "inherit",
        lineHeight: "inherit",
        letterSpacing: "0px",
        wordSpacing: "0px",
        whiteSpace: "pre",
        contain: "strict",
      });
      rowElement.style.position = "absolute";
      rowElement.style.left = "0";
      this.rowElements[y] = rowElement;
      this.rowsLayer?.appendChild(rowElement);
    }
    const geometry = {
      top: `${y * metrics.cellHeight}px`,
      height: `${metrics.cellHeight}px`,
      width: `${metrics.columns * metrics.cellWidth}px`,
    };
    for (const key of ["top", "height", "width"] as const) {
      if (rowElement.style[key] !== geometry[key])
        rowElement.style[key] = geometry[key];
    }
    return rowElement;
  }

  private applyRootStyle(root: HTMLElement, metrics: SurfaceMetrics): void {
    const style = root.style;
    Object.assign(style, scopedBoxStyle);
    style.position = "relative";
    style.overflow = "hidden";
    style.background = webTUITerminalBackgroundColor(metrics.style);
    if (this.forcedColors) style.background = "Canvas";
    style.color = this.forcedColors
      ? "CanvasText"
      : metrics.style.theme.foreground;
    style.font = fontForStyle(metrics.style);
    // Set after `font`: the shorthand resets line-height, and the grid needs
    // every row to be exactly one cell tall.
    style.lineHeight = `${metrics.cellHeight}px`;
    style.letterSpacing = "0px";
    style.wordSpacing = "0px";
    style.fontKerning = "none";
    style.fontSynthesis = "none";
    style.direction = "ltr";
    style.unicodeBidi = "isolate";
    // Ligature-capable monospace fonts would merge runs like "->" into one
    // glyph and break the column grid.
    style.fontVariantLigatures = "none";
    style.userSelect = "text";
  }

  private reconcileImages(
    images: WebHostSurfaceImage[],
    metrics: SurfaceMetrics,
    allowRecoveryRequests: boolean,
  ): void {
    const layer = this.imagesLayer;
    if (!layer) {
      return;
    }

    const next = new Map<string, RenderedImage>();
    const currentMissingImageIds = new Set<string>();
    const newlyMissingImageIds = new Set<string>();
    let decodedBytes = 0,
      payloadBytes = 0;
    const occurrences = new Map<string, number>();
    const previousPayloads = new Map(
      [...this.renderedImages.values()].map((entry) => [entry.id, entry]),
    );
    const currentPayloads = new Map(
      images
        .filter((image) => image.dataBase64 !== undefined)
        .map((image) => [image.id, image.dataBase64!]),
    );
    for (const rawImage of images) {
      if (!isSupportedImageFormat(rawImage.format)) {
        continue;
      }
      const image = {
        ...rawImage,
        dataBase64: rawImage.dataBase64 ?? currentPayloads.get(rawImage.id),
        scalingMode: normalizeScalingMode(rawImage.scalingMode),
      };
      const [boundsX, boundsY, boundsWidth, boundsHeight] = image.bounds;
      const [clipX, clipY, clipWidth, clipHeight] = image.visibleBounds;
      const occurrence = occurrences.get(image.id) ?? 0;
      occurrences.set(image.id, occurrence + 1);
      const placementKey = JSON.stringify([image.id, occurrence]);
      const existing = this.renderedImages.get(placementKey);
      const previousPayload = previousPayloads.get(image.id);
      if (
        boundsWidth <= 0 ||
        boundsHeight <= 0 ||
        clipWidth <= 0 ||
        clipHeight <= 0
      ) {
        continue;
      }
      if (!existing && !previousPayload && image.dataBase64 === undefined) {
        if (!isWebHostImageRecoveryId(image.id)) {
          continue;
        }
        currentMissingImageIds.add(image.id);
        if (!this.reportedMissingImageIds.has(image.id)) {
          newlyMissingImageIds.add(image.id);
        }
        continue;
      }

      const source =
        image.dataBase64 === undefined
          ? previousPayload?.source
          : `data:image/${image.format};base64,${image.dataBase64}`;
      const changed = source !== existing?.source;
      const allocation =
        image.dataBase64 !== undefined && source !== previousPayload?.source
          ? imagePayloadMetrics(image.dataBase64)
          : previousPayload;
      if (!allocation || !source) {
        this.rejectImage(
          "An image payload has invalid or excessive dimensions.",
        );
        continue;
      }
      if (
        next.size >= MAX_DOM_IMAGE_ENTRIES ||
        decodedBytes + allocation.decodedBytes > MAX_DOM_IMAGE_BYTES ||
        payloadBytes + allocation.payloadBytes > MAX_DOM_IMAGE_BYTES
      ) {
        this.rejectImage(
          "The visible image set exceeds the 256-image or 64 MiB image budget.",
        );
        continue;
      }
      decodedBytes += allocation.decodedBytes;
      payloadBytes += allocation.payloadBytes;

      const entry = existing ?? makeImageEntry(image.id);
      entry.container.style.left = `${clipX * metrics.cellWidth}px`;
      entry.container.style.top = `${clipY * metrics.cellHeight}px`;
      entry.container.style.width = `${clipWidth * metrics.cellWidth}px`;
      entry.container.style.height = `${clipHeight * metrics.cellHeight}px`;
      entry.image.style.left = `${(boundsX - clipX) * metrics.cellWidth}px`;
      entry.image.style.top = `${(boundsY - clipY) * metrics.cellHeight}px`;
      entry.image.style.width = `${boundsWidth * metrics.cellWidth}px`;
      entry.image.style.height = `${boundsHeight * metrics.cellHeight}px`;
      entry.image.style.opacity = String(normalizedImageOpacity(image.opacity));

      if (changed) {
        const generation = ++entry.generation;
        entry.source = source;
        entry.decodedBytes = allocation.decodedBytes;
        entry.payloadBytes = allocation.payloadBytes;
        entry.state = "pending";
        entry.container.setAttribute("data-image-state", "pending");
        entry.image.onload = () => {
          if (
            this.renderedImages.get(placementKey) !== entry ||
            entry.generation !== generation
          )
            return;
          const img = entry.image as HTMLImageElement;
          const actualBytes = img.naturalWidth * img.naturalHeight * 4;
          if (actualBytes <= 0 || actualBytes > entry.decodedBytes) {
            entry.state = "failed";
            this.rejectImage(
              "Decoded image dimensions exceed their admitted container dimensions.",
            );
          } else entry.state = "ready";
          entry.container.setAttribute("data-image-state", entry.state);
        };
        entry.image.onerror = () => {
          if (
            this.renderedImages.get(placementKey) !== entry ||
            entry.generation !== generation
          )
            return;
          entry.state = "failed";
          entry.container.setAttribute("data-image-state", "failed");
        };
        try {
          const displayedSource =
            image.format === "gif"
              ? `data:image/gif;base64,${staticGifBase64(source.slice(source.indexOf(",") + 1))}`
              : source;
          entry.image.setAttribute("src", displayedSource);
        } catch {
          entry.image.removeAttribute("src");
          entry.image.onload = null;
          entry.image.onerror = null;
          entry.state = "failed";
          entry.container.setAttribute("data-image-state", "failed");
          this.rejectImage("An image payload has an invalid GIF container.");
        }
      }
      if (layer.children[next.size] !== entry.container)
        layer.insertBefore(entry.container, layer.children[next.size] ?? null);
      next.set(placementKey, entry);
    }

    for (const [id, entry] of this.renderedImages) {
      if (!next.has(id)) {
        releaseImageEntry(entry);
        entry.container.remove();
      }
    }
    this.renderedImages = next;
    for (const id of this.reportedMissingImageIds) {
      if (!currentMissingImageIds.has(id)) {
        this.reportedMissingImageIds.delete(id);
      }
    }
    if (allowRecoveryRequests && newlyMissingImageIds.size > 0) {
      const candidateIds = [...newlyMissingImageIds].sort();
      const admittedIds = this.onImagePayloadMiss(candidateIds);
      const acceptedIds = Array.isArray(admittedIds)
        ? admittedIds
        : candidateIds;
      const candidates = new Set(candidateIds);
      for (const id of acceptedIds) {
        if (candidates.has(id)) {
          this.reportedMissingImageIds.add(id);
        }
      }
    }
  }
}

function normalizedImageOpacity(opacity: number | undefined): number {
  if (opacity === undefined || !Number.isFinite(opacity)) {
    return 1;
  }
  return Math.max(0, Math.min(1, opacity));
}

/**
 * A change key over everything the rendered tree bakes into element styles —
 * grid geometry, font, and theme colors. A key change invalidates every
 * rendered row, so the next paint restyles the root and rebuilds in full.
 */
function metricsKeyFor(metrics: SurfaceMetrics): string {
  return [
    metrics.columns,
    metrics.rows,
    metrics.cellWidth,
    metrics.cellHeight,
    fontForStyle(metrics.style),
    metrics.style.theme.foreground,
    metrics.style.theme.background,
    metrics.style.theme.windowBackground,
    metrics.style.backgroundOpacity,
  ].join("|");
}

function resolveCellStyle(
  style: WebHostSurfaceStyle | undefined,
  metrics: SurfaceMetrics,
  forcedForeground?: string,
): Partial<CSSStyleDeclaration> {
  const forcedColors = forcedForeground !== undefined;
  const elementStyle = {
    position: "relative",
    display: "inline-block",
    verticalAlign: "top",
    contain: "size",
    boxSizing: "border-box",
    padding: "0",
    margin: "0",
    border: "0",
    textAlign: "left",
    float: "none",
    minWidth: "0",
    maxWidth: "none",
    minHeight: "0",
    maxHeight: "none",
    textIndent: "0",
    textTransform: "none",
    fontFamily: "inherit",
    fontSize: "inherit",
    lineHeight: "inherit",
    letterSpacing: "0px",
    wordSpacing: "0px",
    fontKerning: "none",
    fontSynthesis: "none",
    fontVariantLigatures: "none",
    top: "0",
    height: "100%",
    whiteSpace: "pre",
    overflow: "hidden",
    direction: "ltr",
    unicodeBidi: "isolate",
    color: forcedForeground ?? resolvedSurfaceForeground(style, metrics.style),
    backgroundColor: forcedColors
      ? "Canvas"
      : (resolvedSurfaceBackground(style, metrics.style) ?? "transparent"),
    fontWeight: (style?.em ?? 0) & 1 ? "700" : "normal",
    fontStyle: (style?.em ?? 0) & 2 ? "italic" : "normal",
    opacity: forcedColors ? "1" : String(style?.opacity ?? 1),
    forcedColorAdjust: forcedColors ? "none" : "auto",
    textDecorationLine: "none",
    textDecorationStyle: "solid",
    textDecorationColor: resolvedSurfaceForeground(style, metrics.style),
  };
  return elementStyle;
}

function fillContainer(style: CSSStyleDeclaration): void {
  Object.assign(style, scopedBoxStyle, {
    font: "inherit",
    lineHeight: "inherit",
  });
  style.position = "absolute";
  style.left = "0";
  style.top = "0";
  style.width = "100%";
  style.height = "100%";
}

function makeImageEntry(id: string): RenderedImage {
  const container = createElement("div");
  container.className = "webhost-scene__surface-image";
  Object.assign(container.style, scopedBoxStyle);
  container.style.position = "absolute";
  container.style.overflow = "hidden";

  const image = createElement("img");
  Object.assign(image.style, scopedBoxStyle);
  image.style.position = "absolute";
  image.setAttribute("alt", "");
  image.setAttribute("draggable", "false");
  container.appendChild(image);
  return {
    id,
    container,
    image,
    source: "",
    decodedBytes: 0,
    payloadBytes: 0,
    generation: 0,
    state: "pending",
  };
}

function releaseImageEntry(entry: RenderedImage): void {
  entry.generation++;
  entry.state = "evicted";
  entry.image.onload = null;
  entry.image.onerror = null;
  entry.image.removeAttribute("src");
  entry.source = "";
  entry.decodedBytes = entry.payloadBytes = 0;
}

const scopedBoxStyle = {
  display: "block",
  boxSizing: "border-box",
  float: "none",
  minWidth: "0",
  maxWidth: "none",
  minHeight: "0",
  maxHeight: "none",
  margin: "0",
  padding: "0",
  border: "0",
  textAlign: "left",
  textIndent: "0",
  textTransform: "none",
};

function createElement(tagName: string): HTMLElement {
  if (typeof document === "undefined") {
    throw new Error("document is not available");
  }
  return document.createElement(tagName);
}

/** Only a mutation of selected content cancels a live selection. */
function selectionInvalidator(): (element: HTMLElement) => void {
  let selection = globalThis.document?.getSelection?.();
  if (!selection || selection.isCollapsed) return () => {};
  const ranges = Array.from({ length: selection.rangeCount }, (_, index) =>
    selection!.getRangeAt(index),
  );
  return (element) => {
    if (selection && ranges.some((range) => range.intersectsNode(element))) {
      selection.removeAllRanges();
      selection = null;
    }
  };
}

/** Spaces represent every unoccupied grid column; a wide cell contributes its
 * supplied grapheme once, never a second continuation character. */
function copyableRow(
  cells: WebHostSurfaceCell[],
  width: number,
): WebHostSurfaceCell[] {
  const result: WebHostSurfaceCell[] = [];
  let end = 0;
  for (const cell of cells) {
    if (cell[0] > end)
      result.push([end, " ".repeat(cell[0] - end), cell[0] - end, -1]);
    result.push(cell);
    end = cell[0] + Math.max(1, cell[2]);
  }
  if (end < width) result.push([end, " ".repeat(width - end), width - end, -1]);
  return result;
}
